# Generated by Django 5.0.4 on 2024-06-07 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_users_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uni_name', models.CharField(max_length=70)),
                ('prog_name', models.CharField(max_length=70)),
                ('study_mode', models.CharField(choices=[('O', 'Online'), ('C', 'On-Campus')], max_length=10)),
                ('status', models.CharField(choices=[('A', 'Accepted'), ('R', 'Rejected'), ('P', 'Pending')], default=('P', 'Pending'), max_length=10)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.users')),
            ],
        ),
    ]
