# Generated by Django 5.0.4 on 2024-06-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_users_otp_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='otp',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
