# Generated by Django 5.0.4 on 2024-06-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_users_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='otp',
            field=models.IntegerField(null=True),
        ),
    ]
