# Generated by Django 5.0.4 on 2024-06-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_users_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='otp',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
